# Generated by Django 4.2.6 on 2023-11-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_fio_remove_user_verify_code_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default=0, max_length=50, verbose_name='Верификация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, max_length=20, verbose_name='Подтверждение'),
        ),
    ]
